package fermyon:spin-template@0.0.1;

interface types {
    variant error {
        cancel,  // I know it's not truly an error but work with me here
        other(string),
    }
    variant create-mode {
        create-new,
        add-to(string),  // path to manifest to add to
    }
    record run-options {
        mode: create-mode,
        // provided-values: list<tuple<string, string>>, // not needed?  We can respond with these from the UI functions
        use-default-values: bool, // I don't *think* we can handle this within the UI functions because only the template author knows what the default is
    }
    resource execution-context {
        set-variable: func(name: string, value: string);
        evaluate-template: func(template: string) -> result<string, error>;
    }
}

interface template {
    use types.{error, execution-context, run-options};

    variant action {
        copy-file-substituted(string),
        copy-file-to-substituted(tuple<string, string>),
        copy-file-to-raw(tuple<string, string>),
        write-file(tuple<string, string>),
        write-file-binary(tuple<string, list<u8>>),
        create-dir(string),  // normally auto but in case you need an empty directory a la fileserver
        // edit-file(tuple<string, func(existing: string) -> string>), // no! no! no!
        edit-file(tuple<string, edit>),
    }

    resource edit {
        apply: func(text: string, context: borrow<execution-context>) -> result<string, error>;
    }

    run: func(context: borrow<execution-context>, options: run-options) -> result<list<action>, error>;
}

interface ui {
    use types.{error};

    prompt: func(prompt: string, default-value: option<string>) -> string;
    confirm: func(prompt: string, default-value: option<bool>) -> bool;
    select: func(prompt: string, items: list<string>, default-index: option<u8>) -> u8;

    resource file {
        list-all: static func() -> list<file>;
        path: func() -> string;
        read: func() -> result<string, error>;
        read-binary: func() -> result<list<u8>, error>;
    }
}

world run-template {
    import ui;
    export template;
}
